export const COUNTERS = {
    REQUEST_COUNTERS: 'REQUEST_COUNTERS',
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    REQUEST_FAILURE: 'REQUEST_FAILURE',
    FILTER_COUNTERS_BY_TITLE: 'FILTER_COUNTERS_BY_TITLE',
    UPDATE_COUNT_COUNTERS: 'UPDATE_COUNT_COUNTERS',
    ADD_COUNTER: 'ADD_COUNTER',
    REQUEST_ADD_SUCCESS: 'REQUEST_ADD_SUCCESS',
    DELETE_COUNTER: 'DELETE_COUNTER',
    ROW_SELECT: 'ROW_SELECT',
    ROW_DESELECT: 'ROW_DESELECT',
    ROW_RESET: 'ROW_RESET'
}